### ISSUE TITLE
[Question] About the Subdivide function

### ISSUE THREAD

**Issue by PiscesdanAT** [CedricGuillemet/HexagridRelaxing#1]
Hi, I just wanted to know, is there any advantage to using a template for subdivide instead of adding another argument?

Thanks.

**Comment by CedricGuillemet** [comment]
There is a performance advantage in doing so. The value is inlined and the function code is duplicated. It should be slightly faster but I didn't do a benchmark. For functions that get called many times, this can be a win.

**Comment by PiscesdanAT** [comment]
I see, so it shouldn't be an issue when using a language that doesn't have templates.

Thank you.
